apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: my-app
    tier: frontend 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: myapp  
  template:
    metadata:
      labels:
        app: myapp
        type: frontend  
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80  



kubectl apply -f deployment-defination.yml

kubectl get deployments

kubectl rollout status deployment/myapp-deployment

kubectl rollout history deployments


